stage:
  deploy:
    REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'
    MYSQL_USE_SLAVE_CONNECTION: true
    REDIS_USE_SLAVE_CONNECTION: true
  build:
    QUALITY_PATCHES:
      - MDVA-30106
  global:
    SKIP_HTML_MINIFICATION: true
