<?php

// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile
// phpcs:disable Magento2.Templates.ThisInTemplate

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php foreach ($block->getTotals() as $_code => $_total) : ?>
    <?php if ($_total->getBlockName()) : ?>
        <?= $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else :?>
    <tr class="<?= $block->escapeHtmlAttr($_code) ?>">
        <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
            <?php if ($_total->getStrong()) : ?>
                <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
            <?php else : ?>
                <?= $block->escapeHtml($_total->getLabel()) ?>
            <?php endif ?>
        </th>
        <td <?= /* @noEscape */ $block->getValueProperties() ?>
            data-th="<?= $block->escapeHtmlAttr($_total->getLabel()) ?>">
            <?php $value = $block->escapeHtmlAttr($_total->getValue());
             if ($_total->getStrong()) : ?>
                <strong><?= /* @noEscape */ round($value)  ?></strong>
            <?php else : ?>
                <?= /* @noEscape */ round($value) ?>
            <?php endif?>
        </td>
    </tr>
    <?php endif; ?>
<?php endforeach?>
