<?php

$mobileblock = $block->getLayout()->createBlock('Magecomp\Mobilelogin\Block\Login');
$geoCountryCode = $mobileblock->getGeoCountryCode();
$allowCountry = $mobileblock->getApplicableCountryJson();
if ($mobileblock->isEnable()):
    ?>
<div class="create-account-page-main-div fieldset">
    <legend class="legend"><span><?php echo __("Mobile Verification"); ?></span></legend>
    <br>
    <input type="hidden" value="<?php echo $block->getUrl("mobilelogin/index/sentotpbyreg"); ?>" class="setdotpurl"/>
    <input type="hidden" value="<?php echo $block->getUrl("mobilelogin/index/ajaxcheckregotp"); ?>"
           class="checkotpurl"/>
    <div id="create-account-page" class="login-window account-login">
        <div class="mobileget">
            <div class="otp-content fieldset">
                <div class="field mobilenumber required" bis_skin_checked="1">
                    <label for="mobile-mobileget" class="label">
                        <span>Mobile Number</span>
                    </label>

                </div>
                <div class="mobilenumber-reg-text">
                    <input type="text" value="" id="mobile-mobileget" class="mobnumber" name="mobile-mobileget"
                           maxlength="12"/>
                    <input type="hidden" value="" id="regi-mobilenumber" name="mobilenumber"/>
                    <input type="hidden" value="" id="countryreg" name="countryreg"/>
                </div>
                <div class="mobileotpsenderror error1 error">
                    <span><?php echo __("Please Enter Valid Mobile."); ?></span>
                </div>
                <div class="mobileExist error1 error">
                    <span><?php echo __("Mobile Number Already Exist."); ?></span>
                </div>
                <div class="blankerror error1 error" id="blankpage_customer_register">
                    <span><?php echo __("Required fields cannot be empty"); ?></span>
                </div>
                <div class="mobileNotValid error1 error" id="mobileNotValid">
                    <span><?php echo __("Please Enter Valid Mobile Number"); ?></span>
                </div>
            </div>
            <div class="model-bottom">
                <div class="submitbtnajax" id="submitbtnajax">
                    <input type="button" class="regi-sendotp button primary action"
                           value="<?php echo __("Send Otp"); ?>"/>
                </div>
                <div class="progress-indicator">
                             <span class="please-wait" id="reg-sms-please-wait">
                                <img src="<?php echo
                                $block->getViewFileUrl('Magecomp_Mobilelogin::images/ajax-loader.gif'); ?>"
                                     class="v-middle" alt=""/>
                            </span>
                </div>
            </div>
        </div>
        <div class="otpverify" id="otpverify2">
            <div class="otp-content fieldset">
                  <span class="field required">
                    <label for="mobile-otp" class="label">
                      <span><?php echo __('Enter OTP') ?></span>
                     </label>
                    </span>
                <span class="create-account-resend-otp">
                        <label for="resend-mobile-otp" class="label">
                            <span class='resend'><?php echo __("Resend OTP"); ?></span>
                            <span class='sending' id="sending"><?php echo __("Sending OTP..."); ?></span>
                         </label>
                    </span>
                <input type="password" value="" id="mobile-otp" maxlength="<?php echo $block->getOtpStringlenght() ?>"/>
                <div class="checkotperror error1 error">
                    <span><?php echo __("Incorrect OTP, Please Verify Again."); ?></span>
                </div>
                <div class="blankerror blankotperror error1 error">
                    <span><?php echo __("Required fields cannot be empty."); ?></span>
                </div>
                <div class="model-bottom2">
                    <div class="submitbtnajax" id="submitbtnajax1">
                        <input type="button" class="mobileverifyotp button primary action"
                               value="<?php echo __('Verify OTP') ?>"/>
                    </div>
                </div>
                <div class="progress-indicator">
                   <span class="please-wait" id="reg-otp-verify-please-wait">
                     <img src="<?php echo
                        $block->getViewFileUrl('Magecomp_Mobilelogin::images/ajax-loader.gif'); ?>" class="v-middle"
                          alt="Please Wait"/>
                  </span>
                </div>
            </div>
        </div>
        <div class="customer-progress-indicator" id="customer-progress-indicator">
   <span class="customer-please-wait" id="customer-register-wait">
           <img src="<?php echo
            $block->getViewFileUrl('Magecomp_Mobilelogin::images/ajax-loader.gif'); ?>" class="v-middle"
                alt="Please Wait"/>
     </span>
        </div>
        <script>
            require(['jquery', 'mage/translate', 'jquery/ui', 'mage/mage', 'mage/validation'], function ($, $t) {
                var custreginput = document.querySelector("#mobile-mobileget"),
                    custregerrorMsg = document.querySelector("#mobileNotValid");


                $(".form.create.account.form-create-account>div.actions-toolbar > .primary >.action.submit.primary").css("display", "none");
                $(".action.submit.primary").click(function (e) {
                    var mobile = $('#mobile-mobileget').val();
                    if (mobile == null || mobile == '') {
                        $('#mobile-mobileget').addClass('mage-error');
                        $('.blankerror').show();
                    }
                    var mobileotp = $('#mobile-otp').val();
                    if (mobileotp == null || mobileotp == '') {
                        $('#mobile-otp').addClass('mage-error');
                        $('.blankerror').show();
                    }
                });

                // here, the index maps to the error code returned from getValidationError - see readme
                var custregerrorMap = [$t("Invalid number"), $t("Invalid country code"), $t("Too short"), $t("Too long"), $t("Invalid number")];

                // initialise plugin
                var custregiti = window.intlTelInput(custreginput, {
                    initialCountry: "auto",
                    onlyCountries: <?php echo /* @noEscape */ $allowCountry;?>,
                    placeholderNumberType: 'MOBILE',
                    utilsScript: "<?php echo $block->getViewFileUrl('Magecomp_Mobilelogin::js/utils.js'); ?>"
                });
                var countryCode = "<?php echo /* @noEscape */ $geoCountryCode;?>";
                custregiti.setCountry(countryCode);

                var reset = function () {
                    custreginput.classList.remove("error");
                    custregerrorMsg.innerHTML = "";
                };

                // on blur: validate
                custreginput.addEventListener('blur', function () {
                    reset();
                    if (custreginput.value.trim()) {
                        if (custregiti.isValidNumber()) {
                        } else {
                            var custregerrorCode = custregiti.getValidationError();
                            custregerrorMsg.innerHTML = custregerrorMap[custregerrorCode];

                        }
                    }
                });

                function validateMobile(mobile) {
                    var filter = /^((\+[1-9]{1,4}[ \-]*)|(\([0-9]{2,3}\)[ \-]*)|([0-9]{2,4})[ \-]*)*?[0-9]{3,4}?[ \-]*[0-9]{3,4}?$/;
                    if (filter.test(mobile)) {
                        if (mobile.length >= 9 && mobile.length <= 13) {
                            var validate = true;
                        } else {
                            var validate = false;
                        }
                    } else {
                        var validate = false;
                    }
                    return validate;
                }

                jQuery(".resend-mobile-otp").click(function (e) {
                    jQuery(".regi-sendotp").trigger('click');
                });
                jQuery(".regi-sendotp").click(function (e) {

                    var regimobile = jQuery("#mobile-mobileget").val();
                    var url = jQuery(".setdotpurl").val();
                    jQuery(".blankerror").css('display', 'none');
                    jQuery(".mobileNotValid").css('display', 'none');
                    jQuery(".mobileotpsenderror").css('display', 'none');
                    jQuery(".mobileExist").css('display', 'none');
                    jQuery(".resend").css('display', 'none');
                    jQuery(".sending").css('display', 'block');

                    if (!regimobile) {
                        jQuery(".blankerror").css('display', 'block');
                        return false;
                    }
                    if (validateMobile(regimobile) == false) {
                        jQuery(".mobileNotValid").css('display', 'block');
                        return false;
                    }
                    if (jQuery('.otp-content .iti__selected-flag').attr('title') != undefined) {
                        var countrycode = jQuery('.otp-content .iti__selected-flag').attr('title').match(/\d+/)[0];
                    } else {
                        var countrycode = jQuery('.otp-content .selected-flag').attr('title').match(/\d+/)[0];
                    }
                    var mobile = countrycode.concat(regimobile);
                    jQuery(".sendotp").css('display', 'none');
                    jQuery("#reg-sms-please-wait").css('display', 'block');
                    jQuery(this).prop('disabled', true);
                    jQuery.ajax({
                        url: url,
                        type: 'GET',
                        data: {mobile: mobile},
                        success: function (data) {
                            jQuery(".sendotp").css('display', 'block');
                            jQuery("#reg-sms-please-wait").css('display', 'none');

                            if (data.status === true) {

                                jQuery("#otpverify2").css('display', 'block');
                                jQuery("#createmobile").val(mobile);
                                jQuery(".mobileget").css('display', 'block');
                                jQuery(".regi-sendotp").css('display', 'none');
                                document.getElementById("mobile-mobileget").readOnly = true;
                                jQuery("#otpverify2").css('display', 'block');
                                jQuery(".resend").css('display', 'block');
                                jQuery(".sending").css('display', 'none');
                                jQuery("#regi-mobilenumber").val(mobile);
                            } else if (data.status == "exist") {
                                jQuery(".mobileExist").css('display', 'block');
                            } else {
                                jQuery(".mobileotpsenderror").css('display', 'block');
                            }
                            jQuery('.regi-sendotp').prop('disabled', false);
                        },
                        error: function () {
                            jQuery(".sendotp").css('display', 'block');
                            jQuery("#reg-sms-please-wait").css('display', 'none');
                            jQuery(this).prop('disabled', false);
                        }
                    });
                });


            });

        </script>
<?php endif; ?>
