<?php
// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
$product =  $_item->getProduct();

use Auraine\Brands\Model\Resolver\DataProvider\BrandsList;

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$brandsList = $objectManager->create(BrandsList::class);
$brand = (int)$product->getData('brand_name');
$color = null;
$productAttributeOptions = $objectManager->get(
  \Magento\Eav\Model\Config::class
)->getAttribute('catalog_product', 'color');
$options = $productAttributeOptions->getSource()->getAllOptions();
foreach ($options as $option) {
  if ($option['value'] == $product->getData('color')) {
    $color = $option['label'];
    break;
  }
}
$brandName = $brandsList->getBrandFromId($brand);
$actualPrice = (float) $_item->getQtyOrdered()  * (float)$_item->getOriginalPrice();
$specialPrice = (float) $_item->getQtyOrdered()  * (float)$_item->getPrice();
$discountPrice = $actualPrice - $specialPrice;
$imagewidth = 200;
$imageheight = 200;
$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
$image_url = $imageHelper->init($product, 'small_image')
  ->setImageFile($product->getSmallImage())->resize($imagewidth, $imageheight)->getUrl();
?>
<div style="padding: 20px">
  <div style="
                            background-color: #f5f5f5;
                            padding-top: 7px;
                            padding-left: 10px;
                            padding-right: 10px;
                        ">
    <div style="
          width: 74px;
          height: 82px;
          background-color: white;
          display: inline-block;
          vertical-align: top;
        ">
      <img style="width: 72px; height: 80px" src="<?= $image_url; ?>" alt="">
    </div>
    <div style="padding-left: 20px; display: inline-block; width: 70%">
      <div style="
            font-family: Helvetica, Arial, Verdana, Tahoma, sans-serif;
            font-size: 14px;
            font-weight: 400;
            line-height: 12px;
            letter-spacing: 0em;
            color: #787878;
            padding-bottom: 10px;
          ">
        <?=  $brandName; ?>
      </div>
      <div style="
            font-family: Helvetica, Arial, Verdana, Tahoma, sans-serif;
            font-size: 16px;
            font-weight: 400;
            line-height: 18px;
            letter-spacing: 0em;
            padding-bottom: 22px;
          ">
        <?= $block->escapeHtml($_item->getName()) ?>
      </div>
      <div>
        <div style="
              display: inline-block;
              font-family: Helvetica, Arial, Verdana, Tahoma, sans-serif;
              font-size: 14px;
              font-weight: 400;
              line-height: 8px;
              letter-spacing: 0em;
            ">
          QTY: <?= (float) $_item->getQtyOrdered() ?>
        </div>
      <?php if (!empty($color)) {?>
        <div style="
              display: inline-block;
              padding-left: 20px;
              font-family: Helvetica, Arial, Verdana, Tahoma, sans-serif;
              font-size: 14px;
              font-weight: 400;
              line-height: 8px;
              letter-spacing: 0em;
            ">
          Color: <?= $color; ?>
        </div>
        <?php } ?>
      </div>
      <div>
        <div style="
              font-family: Helvetica, Arial, Verdana, Tahoma, sans-serif;
              font-size: 14px;
              font-weight: 400;
              line-height: 16px;
              letter-spacing: 0em;
              padding-top: 25px;
              text-align: left;
              width: 48%;
              display: inline-block;
            ">
          Total
        </div>
        <div style="
              font-family: Helvetica, Arial, Verdana, Tahoma, sans-serif;
              font-size: 14px;
              font-weight: 400;
              line-height: 16px;
              letter-spacing: 0em;
              text-align: right;
              width: 50%;
              display: inline-block;
            ">

          <?= round((float)$actualPrice) ; ?>
        </div>
      </div>
      <?php if ($discountPrice != 0) { ?>
      <div>
        <div style="
              font-family: Helvetica, Arial, Verdana, Tahoma, sans-serif;
              font-size: 14px;
              font-weight: 400;
              line-height: 16px;
              letter-spacing: 0em;
              padding-top: 10px;
              text-align: left;
              width: 48%;
              display: inline-block;
            ">
          Discount
        </div>
        <div style="
              font-family: Helvetica, Arial, Verdana, Tahoma, sans-serif;
              font-size: 14px;
              font-weight: 400;
              line-height: 16px;
              letter-spacing: 0em;
              text-align: right;
              width: 50%;
              display: inline-block;
            ">
          <?= round((float)$discountPrice) ; ?>
        </div>
      </div>
      <?php } ?>
      <hr style="border: 1px solid #d9d9d9">
      <div>
        <div style="
              font-family: Helvetica, Arial, Verdana, Tahoma, sans-serif;
              font-size: 14px;
              font-weight: 400;
              line-height: 16px;
              letter-spacing: 0em;
              padding-top: 10px;
              text-align: left;
              width: 48%;
              display: inline-block;
            ">
          Total
        </div>
        <div style="
              font-family: Helvetica, Arial, Verdana, Tahoma, sans-serif;
              font-size: 14px;
              font-weight: 400;
              line-height: 16px;
              letter-spacing: 0em;
              text-align: right;
              width: 50%;
              display: inline-block;
              padding-bottom: 20px;
            ">
          <?= /* @noEscape */ round($_item->getPrice())  ?>
        </div>
      </div>
    </div>
  </div>
</div>
