name: GitHub-Azure Sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16.x'

      - name: Set up Azure as remote
        run: |
          git remote add azure https://abpl@dev.azure.com/abpl/Glamour%20Book/_git/Test_Repo_for_GIT
          git fetch azure

      - name: Merge GitHub changes into Azure
        run: |
          git merge origin/main
          git merge --no-ff --log --no-edit azure/main

      - name: Push changes to Azure
        run: |
          git push azure HEAD:refs/heads/main --force-with-lease
          git push azure --tags
        env:
          AZURE_REPO_TOKEN: Mp6sncbpgn7yuyuuhdmku3355mgewdmefyafdqqgyjoj3icbskeq

