name: Azure Repo Sync

on:
  push:
    branches: [main]

env:
  AZURE_REPO_URL: 'https://dev.azure.com/abpl/Glamour%20Book/_git/Test_Repo_for_GIT'
  AZURE_REPO_USERNAME: 'abpl'
  AZURE_REPO_PASSWORD: 'swffcsjgsvamhjldpow3ezie4wtcie4eyl7hzkhvohbihraltenq'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          node-version: '16.x'

      - name: Set up Git
        run: |
          git remote add azure $AZURE_REPO_URL
          git config credential.helper store
          echo "${AZURE_REPO_USERNAME}:${AZURE_REPO_PASSWORD}" > ~/.git-credentials

      - name: Push code to Azure Repo
        run: |
          git remote add azure $AZURE_REPO_URL
          git push azure main
          git fetch --all --tags
    
