name: Azure Repo Sync

on:
  push:
    branches: [main]

env:
  AZURE_REPO_USERNAME: abpl
  AZURE_REPO_PASSWORD: swffcsjgsvamhjldpow3ezie4wtcie4eyl7hzkhvohbihraltenq

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          node-version: '16.x'

      - name: Set up Git
        run: |
          git config --global user.name "${{ env.AZURE_REPO_USERNAME }}"
          git config --global user.email "noreply@github.com"
          git config credential.helper store

      - name: Push code to Azure Repo
        run: |
          git remote add azure <AZURE_REPO_URL>
          git fetch --all --tags

