<?php
/** @var $block \Auraine\SalesEmail\Block\DefaultItemsNew */
/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();


$imageSize = (int)$block->getConfig('sales_email/imageconfig/image_resize');
if ($imageSize <=10) {
    $imageSize = 135;
}
$_imagehelper = $block->helper(Magento\Catalog\Helper\Image::class);
if ($childProd = current($_item->getChildrenItems())) {
        $productImage = $_imagehelper->init(
            $childProd->getProduct(),
            'category_page_list',
            ['height' => $imageSize , 'width'=> $imageSize]
        )->getUrl();
} else {
        $productImage = $_imagehelper->init(
            $_item->getProduct(),
            'category_page_list',
            ['height' => $imageSize , 'width'=> $imageSize]
        )->getUrl();
}
?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= /* @noEscape */ __('SKU'); ?>: 
        <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getConfig('sales_email/imageconfig/enabled')):?>
        <p class="sku">
    <img src="<?= /* @noEscape */ $productImage?>" title="<?= $block->escapeHtml($_item->getName()) ?>" 
    alt="<?= $block->escapeHtml($_item->getName()) ?>" />
        </p>
        <?php endif;?>

        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
            <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?= /* @noEscape */ $option['label'] ?></em></strong></dt>
                <dd>
                    <?= /* @noEscape */ nl2br($option['value']) ?>
                </dd>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock):?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty"><?=  $_item->getQtyOrdered() * 1 ?></td>
    <td class="item-price">
        <?= /* @noEscape */ $block->getItemPrice($_item); ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $block->helper(Magento\GiftMessage\Helper\Message::class)
->getGiftMessage($_item->getGiftMessageId())): ?>
<tr>
    <td colspan="3" class="item-extra">
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?= /* @noEscape */ __('Gift Message') ?></h3>
                    <strong><?= /* @noEscape */ __('From:'); ?>
                    </strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                    <br /><strong><?=/* @noEscape */ __('To:'); ?>
                    </strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br /><strong><?=/* @noEscape */ __('Message:'); ?></strong>
                    <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
